#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Split data_fetcher.py back into proper 3-layer architecture.
Run: python _split_v3.py
"""

import os

SRC = r"D:\AIHedgeFund\ai-hedge-fund-main\src\tools\data_fetcher.py"
OUT_CLASSES = r"D:\AIHedgeFund\ai-hedge-fund-main\src\tools\data_classes.py"
OUT_CLEANER = r"D:\AIHedgeFund\ai-hedge-fund-main\src\tools\data_cleaner.py"
OUT_FETCHER = r"D:\AIHedgeFund\ai-hedge-fund-main\src\tools\data_fetcher.py"
FACADE = r"D:\AIHedgeFund\ai-hedge-fund-main\src\tools\a_stock_api.py"

with open(SRC, "r", encoding="utf-8") as f:
    lines = f.readlines()

# ============================================================
# Extract sections by line ranges (1-indexed from earlier scan)
# ============================================================

def section(start, end):
    """Get lines[start-1:end] joined"""
    return "".join(lines[start-1:end])

# Classes: FinancialMetrics (205-274), FinancialLineItem (274-365), PriceBar (365-391)
# NewsItem (627-646), MarginTrade (756-778), LimitUpData (851-876), AStockInfo (968-991)
# Lines 1-54 = imports + constants + get_pro_api
# Lines 1296-1319 = _safe_float, _calc_date

# data_classes.py
classes_header = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
A股数据模型 - FinancialMetrics, FinancialLineItem, PriceBar, NewsItem, MarginTrade, LimitUpData, AStockInfo
Generated by _split_v3.py
"""
from __future__ import annotations
from datetime import datetime
from typing import Optional, Any
import math

'''

classes_content = (
    section(205, 274) + "\n" +
    section(274, 365) + "\n" +
    section(365, 391) + "\n" +
    section(627, 646) + "\n" +
    section(756, 778) + "\n" +
    section(851, 876) + "\n" +
    section(968, 991)
)

with open(OUT_CLASSES, "w", encoding="utf-8") as f:
    f.write(classes_header + classes_content)
n = classes_header.count("\n") + classes_content.count("\n")
print(f"[OK] data_classes.py: {n} lines")

# data_cleaner.py
cleaner_content = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
数据清洗工具 - _safe_float, _pct, _calc_date
Generated by _split_v3.py
"""
from typing import Any
from datetime import datetime
import math

''' + section(1296, 1320) + "\n"

with open(OUT_CLEANER, "w", encoding="utf-8") as f:
    f.write(cleaner_content)
print(f"[OK] data_cleaner.py: {cleaner_content.count(chr(10))} lines")

# data_fetcher.py (lines 1-1295)
fetcher_content = (
    section(1, 1295)
)
with open(OUT_FETCHER, "w", encoding="utf-8") as f:
    f.write(fetcher_content)
print(f"[OK] data_fetcher.py: {fetcher_content.count(chr(10))} lines")

# a_stock_api.py facade (backward compat)
facade = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
A股数据接口 - Facade (backward compatibility layer)
Generated by _split_v3.py

Architecture:
  data_classes.py  - 数据模型 (FinancialMetrics, PriceBar, ...)
  data_cleaner.py  - 数据清洗 (_safe_float, _pct, ...)
  data_fetcher.py  - 数据获取 (Tushare/AKShare API calls)
"""
from src.tools.data_classes import (
    FinancialMetrics, FinancialLineItem, PriceBar,
    NewsItem, MarginTrade, LimitUpData, AStockInfo,
)
from src.tools.data_cleaner import _safe_float
from src.tools.data_fetcher import (
    get_pro_api, normalize_ts_code, parse_ts_code,
    get_prices, prices_to_df, get_price_data,
    get_financial_metrics, _get_financial_from_income,
    get_stock_name_for_ticker, get_company_news, _simple_sentiment,
    get_insider_trades, get_limit_list, get_north_money,
    get_stock_info, filter_st_stocks,
    get_market_cap, get_float_market_cap,
    get_stocks_by_sector, get_16_sector_stocks,
    search_line_items, get_market_context,
    TUSHARE_TOKEN, SECTOR_POOL,
)

__all__ = [
    "FinancialMetrics", "FinancialLineItem", "PriceBar",
    "NewsItem", "MarginTrade", "LimitUpData", "AStockInfo",
    "_safe_float",
    "get_pro_api", "normalize_ts_code", "parse_ts_code",
    "get_prices", "prices_to_df", "get_price_data",
    "get_financial_metrics", "_get_financial_from_income",
    "get_stock_name_for_ticker", "get_company_news", "_simple_sentiment",
    "get_insider_trades", "get_limit_list", "get_north_money",
    "get_stock_info", "filter_st_stocks",
    "get_market_cap", "get_float_market_cap",
    "get_stocks_by_sector", "get_16_sector_stocks",
    "search_line_items", "get_market_context",
    "TUSHARE_TOKEN", "SECTOR_POOL",
]
'''

with open(FACADE, "w", encoding="utf-8") as f:
    f.write(facade)
print(f"[OK] a_stock_api.py (facade): {facade.count(chr(10))} lines")
print("\n[DONE] 3-layer split complete!")
